name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  release_image:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/musl.Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mysundry:latest
